### PR TITLE
Update Contributors.md

### PR DESCRIPTION
**Pull request by Matrix278**

### CODE REVIEW

**Comment by hadnazzar** [comment]
please add your linkedin profile aswell

**Comment by Matrix278** [comment]
> please add your linkedin profile aswell

ok :+1:

**Comment by Matrix278** [comment]
@hadnazzar Should be fine now

**Review by hadnazzar — APPROVED** [review]

**Comment by hadnazzar** [comment]
@Matrix278 thanks for your contributions!

**Comment by Matrix278** [comment]
@hadnazzar Can you please add labels here of `hacktoberfest-accepted` and `hacktoberfest`

**Pull request merged**
